"use client";

import "./globals.css";
import { Provider } from "urql";
import { Client, cacheExchange, fetchExchange } from "@urql/core";

const client = new Client({
  // url: "http://localhost:1337/graphql",
  url: process.env.NEXT_PUBLIC_BACKEND_API_URL,
  exchanges: [cacheExchange, fetchExchange],
});

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider value={client}>
        <body>{children}</body>
      </Provider>
    </html>
  );
}
